DROP TABLE REGIONS CASCADE CONSTRAINTS;
DROP TABLE COUNTRIES CASCADE CONSTRAINTS;
DROP TABLE LOCATIONS CASCADE CONSTRAINTS;
DROP TABLE JOBS CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEES CASCADE CONSTRAINTS;
DROP TABLE DEPARTMENTS CASCADE CONSTRAINTS;

PURGE RECYCLEBIN;

CREATE TABLE REGIONS (
 region_id NUMBER(6) CONSTRAINT REGIONS_PK_region_id PRIMARY KEY,
 region_name VARCHAR2(25)
);

CREATE TABLE COUNTRIES (
 country_id CHAR(2) CONSTRAINT COUNTRIES_PK_country_id PRIMARY KEY,
 country_name VARCHAR2(40),
 region_id NUMBER(6) CONSTRAINT COUNTRIES_FK_region_id REFERENCES REGIONS
);

CREATE TABLE LOCATIONS (
 location_id NUMBER(4) CONSTRAINT LOCATIONS_PK_location_id PRIMARY KEY,
 street_address VARCHAR2(20),
 postal_code VARCHAR2(12),
 city VARCHAR2(30),
 state_province VARCHAR2(25),
 country_id CHAR(2) CONSTRAINT LOCATIONS_FK_country_id REFERENCES COUNTRIES
);

CREATE TABLE JOBS (
 job_id VARCHAR2(10) CONSTRAINT JOBS_PK_jobs_id PRIMARY KEY,
 job_title VARCHAR2(35) CONSTRAINT JOBS_NN_jobs_title NOT NULL,
 min_salary NUMBER(6),
 max_salary NUMBER(6)
);

CREATE TABLE DEPARTMENTS (
 department_id NUMBER(4) CONSTRAINT DEPARTMENT_PK_department_id PRIMARY KEY,
 department_name VARCHAR2(30) CONSTRAINT DEPARTMENT_NN_department_id NOT NULL,
 manager_id NUMBER(6) -- CONSTRAINT DEPARTMENT_FK_manager_id REFERENCES EMPLOYEES
);

CREATE TABLE EMPLOYEES (
 employee_id NUMBER(6) CONSTRAINT EMPLOYEES_PK_employee_id PRIMARY KEY,
 first_name VARCHAR2(20) CONSTRAINT EMPLOYEES_NN_first_name NOT NULL,
 last_name VARCHAR2(25) CONSTRAINT EMPLOYEES_NN_last_name NOT NULL,
 email VARCHAR2(50) CONSTRAINT EMPLOYEES_UK_email UNIQUE,
 phone_number VARCHAR2(20),
 hire_date DATE,
 salary NUMBER(8,2) CONSTRAINT EMPLOYEES_CHECK_salary CHECK(salary>0),
 commission_pct NUMBER(8,2),
 manager_id NUMBER(6),
 job_id VARCHAR2(10),
 department_id NUMBER(4),
 CONSTRAINT EMPLOYEES_FK_manager_id FOREIGN KEY (manager_id) REFERENCES EMPLOYEES (employee_id),
 CONSTRAINT EMPLOYEES_FK_job_id FOREIGN KEY (job_id) REFERENCES JOBS (job_id),
 CONSTRAINT EMPLOYEES_FK_department_id FOREIGN KEY (department_id) REFERENCES DEPARTMENTS (department_id)
);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT DEPARTMENTS_FK_manager_id FOREIGN KEY (manager_id) REFERENCES EMPLOYEES (employee_id); 
